# Generated by Django 6.0.5 on 2026-06-01 06:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aloqa Xabari', 'verbose_name_plural': 'Aloqa Xabarlari'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order'], 'verbose_name': 'Galereya Rasmi', 'verbose_name_plural': 'Galereya Rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': "Hero Bo'lim", 'verbose_name_plural': "Hero Bo'limlar"},
        ),
        migrations.AlterModelOptions(
            name='newsevent',
            options={'ordering': ['-date'], 'verbose_name': 'Yangilik / Tadbir', 'verbose_name_plural': 'Yangiliklar va Tadbirlar'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['menu_order', 'title'], 'verbose_name': 'Sahifa', 'verbose_name_plural': 'Sahifalar'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', '-created_at'], 'verbose_name': 'Ilmiy Maqola', 'verbose_name_plural': 'Ilmiy Maqolalar'},
        ),
        migrations.AlterModelOptions(
            name='researcharea',
            options={'ordering': ['order'], 'verbose_name': "Tadqiqot Yo'nalishi", 'verbose_name_plural': "Tadqiqot Yo'nalishlari"},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Sayt Sozlamalari', 'verbose_name_plural': 'Sayt Sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='statcounter',
            options={'ordering': ['order'], 'verbose_name': 'Statistika', 'verbose_name_plural': 'Statistikalar'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': "Jamoa A'zosi", 'verbose_name_plural': "Jamoa A'zolari"},
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_en',
            field=models.CharField(blank=True, default="Tadqiqotlarni ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_ru',
            field=models.CharField(blank=True, default="Tadqiqotlarni ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_text_uz',
            field=models.CharField(blank=True, default="Tadqiqotlarni ko'rish", max_length=100, null=True, verbose_name='Tugma matni'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha matn"),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_ru',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha matn"),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subtitle_uz',
            field=models.TextField(blank=True, null=True, verbose_name="Qo'shimcha matn"),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Matn'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newsevent',
            name='title_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Kontent'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Meta tavsif'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='page',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract_en',
            field=models.TextField(blank=True, null=True, verbose_name='Annotatsiya'),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Annotatsiya'),
        ),
        migrations.AddField(
            model_name='publication',
            name='abstract_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Annotatsiya'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Mualliflar'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Mualliflar'),
        ),
        migrations.AddField(
            model_name='publication',
            name='authors_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Mualliflar'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Jurnal nomi'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Jurnal nomi'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Jurnal nomi'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Maqola sarlavhasi'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='description_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Footer matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Footer matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Footer matni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_en',
            field=models.CharField(default='Psychophysiology Lab', max_length=200, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_ru',
            field=models.CharField(default='Psychophysiology Lab', max_length=200, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name_uz',
            field=models.CharField(default='Psychophysiology Lab', max_length=200, null=True, verbose_name='Sayt nomi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_uz',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='statcounter',
            name='label_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biografiya'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biografiya'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Biografiya'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qilganmi?"),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Orqa fon rasmi'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_link',
            field=models.CharField(blank=True, default='/research/', max_length=200, verbose_name='Tugma havolasi'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_text',
            field=models.CharField(blank=True, default="Tadqiqotlarni ko'rish", max_length=100, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name="Qo'shimcha matn"),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etilganmi?'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Chop etilganmi?'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='news_type',
            field=models.CharField(choices=[('news', 'Yangilik'), ('event', 'Tadbir'), ('award', 'Mukofot'), ('announcement', "E'lon")], default='news', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='newsevent',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Banner rasmi'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Kontent'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Chop etilganmi?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='menu_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Menyu tartibi'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Meta tavsif'),
        ),
        migrations.AlterField(
            model_name='page',
            name='show_in_menu',
            field=models.BooleanField(default=True, verbose_name="Menyuda ko'rinsinmi?"),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='Annotatsiya'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=500, verbose_name='Mualliflar'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi_link',
            field=models.URLField(blank=True, verbose_name='DOI havolasi'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etilganmi?'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(max_length=300, verbose_name='Jurnal nomi'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pages',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sahifalar'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='PDF fayl'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Maqola sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='volume',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tom'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Yil'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='icon',
            field=models.CharField(choices=[('brain', '🧠 Miya'), ('eye', "👁️ Ko'z"), ('heart', '❤️ Yurak'), ('chart', '📊 Grafik'), ('lab', '🔬 Laboratoriya'), ('signal', '📡 Signal'), ('neuron', '⚡ Neyron'), ('data', "💻 Ma'lumot")], default='brain', max_length=20, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='Footer matni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='researchgate',
            field=models.URLField(blank=True, verbose_name='ResearchGate'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Psychophysiology Lab', max_length=200, verbose_name='Sayt nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter / X'),
        ),
        migrations.AlterField(
            model_name='statcounter',
            name='icon',
            field=models.CharField(default='chart', max_length=50, verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='statcounter',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='statcounter',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='statcounter',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Qiymati'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Biografiya'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='google_scholar',
            field=models.URLField(blank=True, verbose_name='Google Scholar'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='personal_website',
            field=models.URLField(blank=True, verbose_name='Shaxsiy veb-sayt'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='researchgate',
            field=models.URLField(blank=True, verbose_name='ResearchGate'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('pi', 'Asosiy Tadqiqotchi (PI)'), ('postdoc', 'Postdoktorant'), ('phd', 'Doktorant (PhD)'), ('masters', 'Magistrant'), ('undergrad', 'Bakalavr Tadqiqotchi'), ('alumni', 'Bitiruvchi'), ('staff', 'Laboratoriya Xodimi')], default='phd', max_length=20, verbose_name='Lavozimi'),
        ),
    ]
