# Generated by Django 6.0.5 on 2026-06-01 07:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_lab', '0002_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Sarlavha')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Tavsif')),
                ('description_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif')),
                ('description_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tavsif')),
                ('category', models.CharField(choices=[('award', 'Mukofot'), ('grant', 'Grant'), ('recognition', 'Tan olinish'), ('milestone', 'Yutuq'), ('publication', 'Nashr'), ('other', 'Boshqa')], default='award', max_length=20, verbose_name='Kategoriya')),
                ('year', models.PositiveIntegerField(verbose_name='Yil')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Rasm')),
                ('link', models.URLField(blank=True, verbose_name='Havola')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Tavsiya etilganmi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Yutuq / Mukofot',
                'verbose_name_plural': 'Yutuqlar va Mukofotlar',
                'ordering': ['-year', 'order'],
            },
        ),
    ]
