# Generated by Django 6.0.5 on 2026-06-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_lab', '0003_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_secondary',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name="Qo'shimcha Logo (O'ng tomonda)"),
        ),
    ]
