# Generated by Django 6.0.5 on 2026-10-05 06:12

import django.db.models.deletion
from django.db import migrations, models


def copy_existing_navigation(apps, schema_editor):
    Page = apps.get_model('psychology_lab', 'Page')
    MenuItem = apps.get_model('psychology_lab', 'MenuItem')
    routes = [
        ('home', 'Bosh sahifa', 'Главная', 'Home', 'house', 0),
        ('research', 'Tadqiqotlar', 'Исследования', 'Research', 'flask-conical', 10),
        ('team', 'Jamoa', 'Команда', 'Team', 'users', 20),
        ('publications', 'Maqolalar', 'Публикации', 'Publications', 'book-open', 30),
        ('news', 'Yangiliklar', 'Новости', 'News', 'newspaper', 40),
        ('achievements', 'Yutuqlar', 'Достижения', 'Achievements', 'award', 50),
        ('contact', "Bog'lanish", 'Контакты', 'Contact', 'mail', 100),
    ]
    for route, uz, ru, en, icon, order in routes:
        MenuItem.objects.create(
            title=uz, title_uz=uz, title_ru=ru, title_en=en,
            destination_type='route', route_name=route, icon=icon, order=order,
        )
    pages = Page.objects.filter(is_published=True, show_in_menu=True).order_by('menu_order', 'title')
    for index, page in enumerate(pages):
        MenuItem.objects.create(
            title=page.title, title_uz=page.title_uz,
            title_ru=page.title_ru, title_en=page.title_en,
            destination_type='page', page=page, icon='file-text', order=60 + index,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('psychology_lab', '0004_sitesettings_logo_secondary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Sahifa', 'verbose_name_plural': 'Sahifalar'},
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Menyu nomi')),
                ('title_uz', models.CharField(max_length=120, null=True, verbose_name='Menyu nomi')),
                ('title_ru', models.CharField(max_length=120, null=True, verbose_name='Menyu nomi')),
                ('title_en', models.CharField(max_length=120, null=True, verbose_name='Menyu nomi')),
                ('destination_type', models.CharField(choices=[('route', "Tayyor bo'lim"), ('page', 'Oddiy sahifa (CKEditor)'), ('external', 'Tashqi havola'), ('none', 'Faqat ichki menyuni ochish')], default='page', max_length=10, verbose_name='Havola turi')),
                ('route_name', models.CharField(blank=True, choices=[('home', 'Bosh sahifa'), ('research', 'Tadqiqotlar'), ('team', 'Jamoa'), ('publications', 'Maqolalar'), ('news', 'Yangiliklar'), ('achievements', 'Yutuqlar'), ('contact', "Bog'lanish")], max_length=30, verbose_name="Tayyor bo'lim")),
                ('external_url', models.URLField(blank=True, verbose_name='Tashqi havola')),
                ('icon', models.CharField(blank=True, choices=[('house', 'Uy'), ('flask-conical', 'Laboratoriya'), ('users', 'Jamoa'), ('book-open', 'Kitob'), ('newspaper', 'Yangilik'), ('award', 'Mukofot'), ('mail', 'Xat'), ('file-text', 'Sahifa'), ('microscope', 'Mikroskop'), ('brain', 'Miya'), ('eye', "Ko'z"), ('heart', 'Yurak'), ('chart', 'Grafik'), ('lab', 'Kolba'), ('signal', 'Signal'), ('neuron', 'Neyron'), ('data', "Ma'lumot"), ('calendar', 'Taqvim'), ('map-pin', 'Manzil'), ('phone', 'Telefon')], help_text="Menyu nomi yonida ko'rinadigan ikonka.", max_length=40, verbose_name='Ikonka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi?')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Yangi oynada ochilsinmi?')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='psychology_lab.page', verbose_name='Oddiy sahifa')),
                ('parent', models.ForeignKey(blank=True, help_text="Ichki menyu uchun bosh bandni tanlang. Faqat bir daraja qo'llanadi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='psychology_lab.menuitem', verbose_name='Bosh menyu')),
            ],
            options={
                'verbose_name': 'Menyu bandi',
                'verbose_name_plural': 'Menyu va ichki menyular',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(copy_existing_navigation, migrations.RunPython.noop),
        migrations.RemoveField(model_name='page', name='menu_order'),
        migrations.RemoveField(model_name='page', name='show_in_menu'),
    ]
